app.py
from flask import Flask, render_template
import controllers

# Initialize Flask app with the template folder address
app = Flask(__name__, template_folder='templates')

app.register_blueprint(controllers.main)

app.secret_key = 'super secret key'
# Listen on external IPs
# For us, listen to port 3000 so you can just run 'python app.py' to start the server
if __name__ == '__main__':
    # listen on external IPs
    app.run(host='0.0.0.0', port=3000, debug=True)

controllers/__init__.py
from main import *

controllers/extra.py
import MySQLdb
import MySQLdb.cursors

def connect_to_database():
  options = {
    'host': 'localhost',
    'user': 'root',
    'passwd': 'root',
    'db': 'test_db',
    'cursorclass' : MySQLdb.cursors.DictCursor
  }
  db = MySQLdb.connect(**options)
  db.autocommit(True)
  return db

db = connect_to_database()

controllers/main.py
from flask import *
from extra import db
import hashlib
import uuid

main = Blueprint('main', __name__, template_folder='templates')

@main.route('/')
def main_route():
    return render_template('index.html')

@main.route('/login', methods=['POST', 'GET'])
def login_route():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        cur = db.cursor()
        cur.execute('SELECT * FROM User WHERE username=%s;', [username])

        if cur.rowcount != 1:
            return render_template('login.html', userNameNotExist=True)

        user_info = cur.fetchone()

        salted_password = user_info['password'].split('$', 2)
        algorithm = salted_password[0]
        salt = salted_password[1]
        hashed_password = salted_password[2]

        m = hashlib.new(algorithm)
        m.update(salt + password)
        password_to_be_verified = m.hexdigest()

        if password_to_be_verified != hashed_password:
            return render_template('login.html', passwordWrong=True)

        session['username'] = username
        return redirect(url_for('main.main_route'))
    return render_template('login.html')

@main.route('/logout', methods=['GET'])
def logout_route():
    if 'username' in session:
        session.pop('username', None)

    return redirect(url_for('main.main_route'))

@main.route('/signup', methods=['GET', 'POST'])
def signup_route():
    if 'username' in session:
        return redirect(url_for('main.main_route'))

    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        cur = db.cursor()
        cur.execute('SELECT * FROM User WHERE username=%s;', [username])

        if cur.rowcount != 0:
            return render_template('signup.html', userNameExists=True)

        algorithm = 'sha512'
        salt = uuid.uuid4().hex

        m = hashlib.new(algorithm)
        m.update(salt + password)
        password_hash = m.hexdigest()
        password_to_be_stored = '$'.join([algorithm, salt, password_hash])

        cur.execute('INSERT INTO User (username, password) VALUES(%s, %s);', (username, password_to_be_stored))

        return render_template('index.html')

    return render_template('signup.html')

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>

    <link rel="stylesheet" href="/static/css/styleSignIn.css" />

    <title>Taskash</title>
</head>
<body>
  <div class="center">
    {% block content %}{% endblock %}
  </div>
  <script type="text/javascript" src="/static/js/main.js"></script>
  {% if 'username' in session %}
    <a href='{{ url_for('main.logout_route') }}'>Logout</a>
  {% endif %}
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
    {% if 'username' in session %}
        <p class="center">
            Logged in as {{ session['username'] }}
        </p>
    {% endif %}
    <p class="center">
      Welcome!
    </p>

    <a href={{ url_for('main.login_route') }}>Login</a>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}
    <title>Taskash|Log in</title>
    {% if userNameNotExist %}
        <p class="center">
            Username does not exist
        </p>
    {% endif %}

    {% if passwordWrong %}
        <p class="center">
            Password is wrong
        </p>
    {% endif %}

    <a href='{{ url_for('main.signup_route') }}'>Sign up</a>

    <body>
      <div class="container">
      <div class="login">
      	<h1 class="login-heading">
          <strong>Welcome To Taskash. Ready to hire or work? Please sign in.</strong> </h1>
          <form method="post" action="{{ url_for('main.login_route') }}" id="login_form">
            <input type="text" name="username" placeholder="Username" required="required" class="input-txt" />
              <input type="password" name="password" placeholder="Password" required="required" class="input-txt" />
              <div class="login-footer">
                 <a href="#" class="lnk">
                  <span class="icon icon--min">(๑>◡<๑)</span>
                  Today is a pretty day
                </a>

                </div>
          </form>
          <button type = "submit" class="btn btn--right" form="login_form">Sign in</button>
      </div>
    </div>
    </body>


{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% block content %}
    <title>Taskash|Sign up</title>

    {% if userNameExists %}
        <p class="center">
            Username already exists
        </p>
    {% endif %}

    <form method="post" action="{{ url_for('main.signup_route') }}" id="signup_form">
      <input type="text" name="username" placeholder="Username" required="required" class="input-txt" />
        <input type="password" name="password" placeholder="Password" required="required" class="input-txt" />
        <div class="login-footer">
           <a href="#" class="lnk">
            <span class="icon icon--min">(๑>◡<๑)</span>
            Today is a pretty day
          </a>

          </div>
    </form>
    <button type = "submit" class="btn btn--right" form="signup_form">Sign up</button>

{% endblock %}